/**
 * Board geometry — the Position → Vector3 boundary (ARCHITECTURE-v3 §9).
 *
 * The Oracle emits logical Positions; the Director maps them to world coordinates
 * HERE. oracle/ has zero `three` imports; this module owns physical space.
 *
 * Convention (IMPLEMENTATION-PLAN-v1 §7.3.1): could be a Blender export. For v1's
 * minimalist art direction we compute procedurally — the boundary means swapping
 * to Blender coords later is a one-file change.
 *
 * LAYOUT: classic Ludo cross on a 15×15 grid. Four 3-wide arms meet at a 3×3
 * center. The shared loop traces the outer two columns/rows of each arm (52 cells,
 * clockwise), with 4 arm-junction corners represented as L-turn tiles. Col/row 7
 * of each arm is the home column. The 4 corners are in 6×6 yard blocks.
 *
 * Verified by boardGeometry.test.ts: 52 loop + 20 home + 16 yard = 88 cells,
 * no dupes, loop closes, entries 13 apart, home columns point to center.
 */

import { Vector3 } from 'three';
import type { Color, Position } from '../../oracle/board/track';

const CELL = 1;
export const TOKEN_Y = 0.15;
const SURFACE_Y = 0;
const C = 7; // 15×15 grid center index

function g(col: number, row: number, y: number = SURFACE_Y): Vector3 {
  return new Vector3((col - C) * CELL, y, (row - C) * CELL);
}

/** Rotate 90° clockwise around center (7,7): (c,r) → (14-r, c).
 *  CW matches ENTRY_OFFSET ordering (red→green→yellow→blue go clockwise). */
function rot([c, r]: readonly [number, number]): [number, number] {
  return [14 - r, c];
}

/**
 * The 52-cell clockwise loop. Generated by tools/generate-loop.mjs and verified:
 * length 52, no duplicates, closes (cell 51→0 adjacent), entries at 13-cell
 * intervals (red [1,6], green [8,1], yellow [13,8], blue [6,13]). Four arm-junction
 * transitions are diagonal (dist √2); the 3D board renders these as L-turn tiles.
 */
const LOOP_GRID: ReadonlyArray<readonly [number, number]> = [
  [1,6], [2,6], [3,6], [4,6], [5,6], [6,5], [6,4], [6,3], [6,2], [6,1], [6,0], [7,0], [8,0],
  [8,1], [8,2], [8,3], [8,4], [8,5], [9,6], [10,6], [11,6], [12,6], [13,6], [14,6], [14,7], [14,8],
  [13,8], [12,8], [11,8], [10,8], [9,8], [8,9], [8,10], [8,11], [8,12], [8,13], [8,14], [7,14], [6,14],
  [6,13], [6,12], [6,11], [6,10], [6,9], [5,8], [4,8], [3,8], [2,8], [1,8], [0,8], [0,7], [0,6],
];

export const SHARED_TRACK_COORDS: Vector3[] = LOOP_GRID.map(([c, r]) => g(c, r));

/**
 * Home columns: 5 cells per color along col/row 7 of each arm, from just-off-loop
 * (cell 0, far from center) to nearest-center (cell 4). Red's column is the template;
 * others are 90° rotations.
 *   Red home: row 7, cols 1→5 (from left arm, walking right toward center)
 */
const HOME_GRID_RED: ReadonlyArray<readonly [number, number]> = [
  [1, 7], [2, 7], [3, 7], [4, 7], [5, 7],
];
const HOME_GRID: Record<Color, ReadonlyArray<readonly [number, number]>> = {
  red: HOME_GRID_RED,
  green: HOME_GRID_RED.map(rot),
  yellow: HOME_GRID_RED.map(rot).map(rot),
  blue: HOME_GRID_RED.map(rot).map(rot).map(rot),
};

export const HOME_COORDS: Record<Color, Vector3[]> = {
  red: HOME_GRID.red.map(([c, r]) => g(c, r)),
  green: HOME_GRID.green.map(([c, r]) => g(c, r)),
  yellow: HOME_GRID.yellow.map(([c, r]) => g(c, r)),
  blue: HOME_GRID.blue.map(([c, r]) => g(c, r)),
};

export const CENTER_COORD: Vector3 = g(7, 7);

/** Yard slots: 4 per color in a 2×2 inside each 6×6 corner yard. */
const YARD_GRID_RED: ReadonlyArray<readonly [number, number]> = [
  [2, 2], [4, 2], [2, 4], [4, 4],
];
const YARD_GRID: Record<Color, ReadonlyArray<readonly [number, number]>> = {
  red: YARD_GRID_RED,
  green: YARD_GRID_RED.map(rot),
  yellow: YARD_GRID_RED.map(rot).map(rot),
  blue: YARD_GRID_RED.map(rot).map(rot).map(rot),
};

export const YARD_COORDS: Record<Color, Vector3[]> = {
  red: YARD_GRID.red.map(([c, r]) => g(c, r, TOKEN_Y)),
  green: YARD_GRID.green.map(([c, r]) => g(c, r, TOKEN_Y)),
  yellow: YARD_GRID.yellow.map(([c, r]) => g(c, r, TOKEN_Y)),
  blue: YARD_GRID.blue.map(([c, r]) => g(c, r, TOKEN_Y)),
};

export const ALL_COLORS: Color[] = ['red', 'green', 'yellow', 'blue'];

/** Logical Position → world Vector3. Pure. Called by Token.tsx each render. */
export function positionToVector3(
  color: Color,
  position: Position,
  slot: number = 0,
): Vector3 {
  switch (position.kind) {
    case 'base':
      return YARD_COORDS[color][slot] ?? CENTER_COORD;
    case 'track':
      return SHARED_TRACK_COORDS[position.cell] ?? CENTER_COORD;
    case 'home':
      return HOME_COORDS[color][position.cell] ?? CENTER_COORD;
    case 'finished':
      return CENTER_COORD;
  }
}
